### ISSUE TITLE
Configuration Checks 報錯

### ISSUE THREAD

**Issue by Vdragon** [ntouind/cloud.ind.ntou.edu.tw#20]
![_071](https://cloud.githubusercontent.com/assets/1192163/8126978/f38ff12c-1125-11e5-946e-e86b1e16ffe0.png)
https://cloud.ind.ntou.edu.tw/owncloud/index.php/settings/admin
如題。

**Comment by Vdragon** [comment]
### 環境
- Google Chrome stable
- Ubuntu 14.04
- 匯入 SSL 憑證於 Google Chrome 中
- 帳號：Ｖ字龍

### 錯誤訊息二

![_072](https://cloud.githubusercontent.com/assets/1192163/8127163/4243fc7c-1127-11e5-9e44-8635531fb930.png)

**Comment by pkriachu** [comment]
Done.
